### ISSUE TITLE
Doesn't work to remove tags if tag title has spaces in them?

### ISSUE THREAD

**Issue by Maximus225** [LunarLite/CWSBot-C-#38]
How do even users manage to create a tag with spaces? Shouldn't title be one word? Hacks? Anyway refer to #cws_bot_tests channel in the main CWS guild for reference.

**Comment by Maximus225** [comment]
NVM, this was solvable by adding ""

**Comment by Izumemori** [comment]
Moved this to the [new repository](https://github.com/trinitrot0luene/Sparky/issues/2), due to it being a valid issue
